name: Build and Release

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout codebase
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.1'

    - name: Build
      run: |
        ./build.sh
    
    - name: Create ZIP archive
      shell: bash
      run: |
        pushd output || exit 1
        touch -mt $(date +%Y01010000) *
        zip -9vr ../libs.zip .
        popd || exit 1
        FILE=./libs.zip
        DGST=$FILE.dgst
        for METHOD in {"md5","sha1","sha256","sha512"}
        do
          openssl dgst -$METHOD $FILE | sed 's/([^)]*)//g' >>$DGST
        done

    - name: Upload files to Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: libs
        path: |
          ./libs.zip
          
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      if: github.event_name == 'release'
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./libs.zip*
        tag: ${{ github.ref }}
        file_glob: true
